### ISSUE TITLE
.NET Core/Standard support

### ISSUE THREAD

**Issue by agc93** [FoundatioFx/Foundatio.AzureStorage#1]
Other parts of Foundatio support .NET Standard 1.5, which makes it usable for .NET Core applications, but this library currently doesn't.

The [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) package this one uses also now supports .NET Standard. Is there anything preventing .NET Standard support for this package?

**Comment by niemyjski** [comment]
I think it was because odata doesn't officially support net standard even though they have a work around for it and that lib supports it. Would you mind submitting a pr for this? I think all you'd need to do is update the csproj.

**Comment by agc93** [comment]
I tried updating the csproj and got some weird build behaviour, but I'll give it a shot and submit a PR if I can get it working.

**Comment by niemyjski** [comment]
Much appreciated.

**Comment by agc93** [comment]
I've updated the `csproj` and it looks like the behaviour of the `WindowsAzure.Storage` library actually varies between .NET 4.6 and .NET Standard 1.5, there's a series of constructors and methods with (often quite wildly) different signatures, and I don't really know enough of the inner workings of this to change the behaviour to suit, short of conditional compilation and a lot of guesswork..

![image](https://cloud.githubusercontent.com/assets/1369269/26522251/b6067daa-433f-11e7-9398-48b8f2dd397b.png)

**Comment by niemyjski** [comment]
Thanks for the update, sounds like they broke lots of api's :\. We'll have to take a pass at this soon. We have a common compiler directive we use on netstandard https://github.com/exceptionless/Foundatio/blob/master/build/common.props#L12 If you wanted to try and compile under netstandard. Also, might be worth logging an issue on the azure storage issue tracker asking why they broke so much :)

**Comment by agc93** [comment]
Thanks @niemyjski ! Looking through the issues on the Azure Storage repo, I see you've been doing this dance for a while :+1: 

Looks like they're keeping [#338](https://github.com/Azure/azure-storage-net/issues/338) for parity items at least!

To be brutally honest, I'm probably not familiar enough with the Azure SDK to get too far on this one, even with conditional compilation (hence originally wanting to use this library :wink: ).

**Comment by niemyjski** [comment]
I'll try and take a stab at this but I gotta finish up some things first.
